# 00. TensorFlow Fundamentals Exercises

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [3]:
vector = tf.constant([1, 2, 3, 4])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [4]:
scalar = tf.constant(13)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [5]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [6]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [12]:
tensor.shape, tf.size(tensor), tensor.ndim

(TensorShape([2, 2, 3]), <tf.Tensor: shape=(), dtype=int32, numpy=12>, 3)

In [18]:
tf.random.set_seed(42)
random_tensor_1 = tf.random.uniform([5, 300])
random_tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [19]:
random_tensor_2 = tf.random.uniform([5, 300])
random_tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
        0.9212563 ],
       [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
        0.51477313],
       [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
        0.9892651 ],
       [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
        0.8280058 ],
       [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
        0.2584542 ]], dtype=float32)>

In [21]:
tf.multiply(random_tensor_1, random_tensor_2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[4.57146466e-01, 2.13658452e-01, 3.28531623e-01, ...,
        2.17384368e-01, 2.51955122e-01, 3.40777524e-02],
       [1.45614594e-01, 3.09705492e-02, 6.57417625e-02, ...,
        2.36865208e-01, 9.56212804e-02, 1.13281950e-01],
       [7.73395528e-04, 1.34753399e-02, 7.99194753e-01, ...,
        1.22185037e-01, 4.81487900e-01, 7.18945917e-03],
       [6.55430436e-01, 5.76979630e-02, 9.58052557e-03, ...,
        6.53199196e-01, 5.08804396e-02, 7.79080987e-01],
       [5.81960231e-02, 1.10622704e-01, 2.62571156e-01, ...,
        6.09022558e-01, 1.02241419e-01, 1.14069067e-01]], dtype=float32)>

In [22]:
tf.multiply(random_tensor_1, 2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[1.3291242 , 0.88201356, 0.705765  , ..., 0.62820935, 1.518707  ,
        0.07398105],
       [1.064048  , 0.5825989 , 0.21143532, ..., 1.0810459 , 0.6285145 ,
        0.4401238 ],
       [0.16808414, 0.07229209, 1.9546425 , ..., 0.4303329 , 1.9572196 ,
        0.01453495],
       [1.479389  , 1.3306344 , 0.1575656 , ..., 1.4235466 , 0.14027143,
        1.881825  ],
       [0.3172269 , 0.24048066, 0.5443647 , ..., 1.7649758 , 0.2864976 ,
        0.88270235]], dtype=float32)>

In [24]:
tf.matmul(random_tensor_1, tf.transpose(random_tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

In [26]:
tf.tensordot(tf.transpose(random_tensor_1), random_tensor_2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.317161  , 0.61993605, 1.2612379 , ..., 1.5290778 , 1.0735596 ,
        1.6227092 ],
       [1.0170685 , 0.42642498, 0.8181824 , ..., 1.1469344 , 0.8212255 ,
        1.1739546 ],
       [0.45034647, 0.8037954 , 1.4656199 , ..., 1.105671  , 0.88152766,
        1.481925  ],
       ...,
       [1.3204696 , 1.1634867 , 1.7423928 , ..., 1.8386563 , 1.5207756 ,
        1.5979093 ],
       [0.73207504, 0.90400356, 1.8493464 , ..., 1.3821819 , 0.98218614,
        1.924531  ],
       [1.0814031 , 0.5316744 , 0.7174167 , ..., 1.2942287 , 1.0804075 ,
        1.0476992 ]], dtype=float32)>