<a href="https://colab.research.google.com/github/sakshamkumar1/tensorflow-notebooks/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.


## Introduction to Tensors



In [1]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check te number of dimensions of a tensor 
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
matrix2 = tf.constant([[1, 2],
                       [3, 4]], dtype=tf.float32)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

## Creating tensors with tf.Variable

In [13]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# changeable_tensor[0] = 7
# changeable_tensor
# ----Gives error----

In [15]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# ----Gives error----
# unchangeable_tensor[0].assign(7)

### Creating random tensors





In [17]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [18]:
# Shuffle a tensor( valuable for when we want to shuffle our data so the inherent order does not affect the learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

⛳ **Exercise** Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed

Practice creating 5 random tensors and shuffle them.

In [19]:
tf.random.normal([1])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-1.0555294], dtype=float32)>

In [20]:
not_shuffled_1 = tf.constant([[1, 2],
                              [3, 4],
                              [5, 6]])
tf.random.shuffle(not_shuffled_1, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [21]:
not_shuffled_2 = tf.random.normal([4, 3], seed=42)
not_shuffled_2

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.28077507, -0.13775212, -0.6763296 ],
       [ 0.02458041, -0.8935846 , -0.8284734 ],
       [ 1.2068944 ,  1.3810157 , -1.4557977 ],
       [-0.24621388, -1.3608406 ,  1.0879604 ]], dtype=float32)>

In [22]:
tf.random.set_seed(42)
tf.random.normal([4, 3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 ],
       [-1.4075519 , -2.3880599 , -1.0392479 ],
       [-0.5573232 ,  0.539707  ,  1.6994323 ],
       [ 0.28893656, -1.5066116 , -0.2645474 ]], dtype=float32)>

In [23]:
tf.random.set_seed(42)
tf.random.normal([3, 3], seed=42)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3148774 , -0.15421568,  0.91138786],
       [-0.7991441 , -0.10875293,  0.28436786],
       [ 0.7661625 , -0.621129  ,  0.9974318 ]], dtype=float32)>

In [24]:
tf.random.set_seed(42)
random_shuffled_3 = tf.constant([[7, 10, 12],
                                [1, 5, 9],
                                [13, 15, 22]])
tf.random.shuffle(random_shuffled_3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  5,  9],
       [13, 15, 22],
       [ 7, 10, 12]], dtype=int32)>

In [25]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [26]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [27]:
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [28]:
tf.zeros((10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

In [29]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [30]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [31]:
A.ndim

3

## Getting information from tensors

* Shape
- Rank
* Axis or dimension
* Size

In [32]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [34]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [35]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


In [36]:
rank_4_tensor[0].shape

TensorShape([3, 4, 5])

## Indexing tensors

In [37]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [38]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [40]:
rank_2_tensor = tf.zeros(shape=[3, 2])
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [41]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [42]:
rank_2_tensor.shape, rank_2_tensor.ndim, tf.size(rank_2_tensor), rank_2_tensor.dtype

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>, tf.int32)

In [43]:
tf.size(rank_2_tensor).numpy()

4

In [44]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [45]:
# Add an extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [46]:
rank_2_tensor[tf.newaxis, ...]

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [47]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [48]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**

In [49]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [50]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [51]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [52]:
# We can use tensorflow built-in functions too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [53]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

**Matrix multiplication**

In [54]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [55]:
tensor_1 = tf.constant([[1, 2, 5],
                       [7, 2, 1],
                       [3, 3, 3]])
tensor_2 = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])
print(tensor_1, tensor_2)

tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32) tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)


In [56]:
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [57]:
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [58]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [59]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [60]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [61]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

**The dot product**

* tf.matmul()
* tf.tensordot()

In [62]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [63]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [64]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [65]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

### Changing the datatype of a tensor

In [66]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [67]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [68]:
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [69]:
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [70]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregrating tensors

In [71]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [72]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [73]:
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [74]:
tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [75]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [76]:
tf.reduce_mean(C)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [77]:
tf.reduce_sum(C)

<tf.Tensor: shape=(), dtype=int32, numpy=17>

In [78]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([17, 54, 11, 30, 89, 96, 96, 34, 84, 98, 74, 83, 75, 70, 46, 63, 78,
       66, 35, 57, 22, 96,  1,  9, 45, 41, 99, 51, 78, 87, 47,  9, 39, 96,
       19,  5, 60, 53, 42, 70, 77, 77, 23, 71,  8, 52, 95, 97, 32, 48])>

In [79]:
tf.reduce_min(E), tf.reduce_max(E), tf.reduce_mean(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=56>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2805>)

In [80]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([17, 54, 11, 30, 89, 96, 96, 34, 84, 98, 74, 83, 75, 70, 46, 63, 78,
       66, 35, 57, 22, 96,  1,  9, 45, 41, 99, 51, 78, 87, 47,  9, 39, 96,
       19,  5, 60, 53, 42, 70, 77, 77, 23, 71,  8, 52, 95, 97, 32, 48])>

In [81]:
E = tf.cast(E, dtype=tf.float32)
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([17., 54., 11., 30., 89., 96., 96., 34., 84., 98., 74., 83., 75.,
       70., 46., 63., 78., 66., 35., 57., 22., 96.,  1.,  9., 45., 41.,
       99., 51., 78., 87., 47.,  9., 39., 96., 19.,  5., 60., 53., 42.,
       70., 77., 77., 23., 71.,  8., 52., 95., 97., 32., 48.],
      dtype=float32)>

In [82]:
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=858.21>

In [83]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=29.295221>

In [84]:
import tensorflow_probability as tfp

tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=858.21>

In [85]:
tfp.stats.stddev(E)

<tf.Tensor: shape=(), dtype=float32, numpy=29.295221>

### Find the positional maximum and minimum

In [86]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [87]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [88]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [89]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [90]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [91]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [92]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [93]:
np.random.rand(30)[tf.argmin(F)]

0.559330007968733

In [94]:
rand_tens = tf.constant(np.random.rand(30))
rand_tens

<tf.Tensor: shape=(30,), dtype=float64, numpy=
array([0.55731123, 0.15664573, 0.77447118, 0.05992234, 0.13334285,
       0.9852125 , 0.0028647 , 0.87711543, 0.21352712, 0.82583472,
       0.08895776, 0.2828442 , 0.9494384 , 0.47451373, 0.07152157,
       0.42082196, 0.17543166, 0.00559946, 0.99670208, 0.58271469,
       0.3894102 , 0.25442047, 0.08694678, 0.86833362, 0.88666359,
       0.39620098, 0.60522039, 0.99690095, 0.8921879 , 0.43134998])>

In [95]:
tf.argmin(rand_tens)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [96]:
rand_tens[tf.argmin(rand_tens)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.002864704872128754>

In [97]:
tf.argmax(rand_tens)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [98]:
rand_tens[tf.argmax(rand_tens)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9969009504703511>

## Squeezing a tensor (removing all single dimensions)

In [99]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[1, 1, 1, 50]))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [100]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [101]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [102]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensor

In [103]:
some_list = [0, 1, 2, 3] 

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [104]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, 4, on_value="I love deep learning!", off_value="I also love chess!")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning!', b'I also love chess!',
        b'I also love chess!', b'I also love chess!'],
       [b'I also love chess!', b'I love deep learning!',
        b'I also love chess!', b'I also love chess!'],
       [b'I also love chess!', b'I also love chess!',
        b'I love deep learning!', b'I also love chess!'],
       [b'I also love chess!', b'I also love chess!',
        b'I also love chess!', b'I love deep learning!']], dtype=object)>

In [105]:
tf.one_hot([0, 1, 2], depth=4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [106]:
tf.one_hot([0, 1, 2, 3, 4], depth=2)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [107]:
tf.one_hot([0, 1, 2, 3, 4], depth=3)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [108]:
tf.one_hot(list(range(0, 5)), depth=5, on_value=13, off_value=1)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[13,  1,  1,  1,  1],
       [ 1, 13,  1,  1,  1],
       [ 1,  1, 13,  1,  1],
       [ 1,  1,  1, 13,  1],
       [ 1,  1,  1,  1, 13]], dtype=int32)>

### Squaring, log, square root

In [109]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [110]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [111]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [112]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [113]:
tf.math.count_nonzero(H)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [114]:
tf.cumsum(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)>

In [115]:
tf.sin(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([ 0.841471  ,  0.90929747,  0.14112   , -0.7568025 , -0.9589243 ,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.4121185 ], dtype=float32)>

### Tensors and NumPy

In [116]:
J = tf.constant(np.array([3., 7., 10]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [117]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [118]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [119]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [120]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [121]:
### Finding access to GPUs

In [122]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [124]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [125]:
!nvidia-smi

Thu Mar 30 15:46:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P0    27W /  70W |    341MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------