In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
X = tf.range(-100, 101, 1)
X

<tf.Tensor: shape=(201,), dtype=int32, numpy=
array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1,    0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
         10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
     

In [ ]:
y = 2 * (X ** 2) + 3 * X + 4

In [ ]:
y

<tf.Tensor: shape=(201,), dtype=int32, numpy=
array([19704, 19309, 18918, 18531, 18148, 17769, 17394, 17023, 16656,
       16293, 15934, 15579, 15228, 14881, 14538, 14199, 13864, 13533,
       13206, 12883, 12564, 12249, 11938, 11631, 11328, 11029, 10734,
       10443, 10156,  9873,  9594,  9319,  9048,  8781,  8518,  8259,
        8004,  7753,  7506,  7263,  7024,  6789,  6558,  6331,  6108,
        5889,  5674,  5463,  5256,  5053,  4854,  4659,  4468,  4281,
        4098,  3919,  3744,  3573,  3406,  3243,  3084,  2929,  2778,
        2631,  2488,  2349,  2214,  2083,  1956,  1833,  1714,  1599,
        1488,  1381,  1278,  1179,  1084,   993,   906,   823,   744,
         669,   598,   531,   468,   409,   354,   303,   256,   213,
         174,   139,   108,    81,    58,    39,    24,    13,     6,
           3,     4,     9,    18,    31,    48,    69,    94,   123,
         156,   193,   234,   279,   328,   381,   438,   499,   564,
         633,   706,   783,   864,   949,  1

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, name="hidden_layer_1", input_shape=[1], activation="relu"),
    tf.keras.layers.Dense(5, name="hidden_layer_2", activation="relu"),
    tf.keras.layers.Dense(1, name="output_layer", activation="relu")
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=["mae"])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_layer_1 (Dense)      (None, 10)                20        
                                                                 
 hidden_layer_2 (Dense)      (None, 5)                 55        
                                                                 
 output_layer (Dense)        (None, 1)                 6         
                                                                 
Total params: 81
Trainable params: 81
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X.numpy(), y.numpy(), test_size=0.2)

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((160,), (160,), (41,), (41,))

In [ ]:
model.fit(X_train, y_train, epochs=500, verbose=1)

Epoch 1/500
5/5 [==============================] - 2s 10ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 2/500
5/5 [==============================] - 0s 12ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 3/500
5/5 [==============================] - 0s 17ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 4/500
5/5 [==============================] - 0s 14ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 5/500
5/5 [==============================] - 0s 10ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 6/500
5/5 [==============================] - 0s 10ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 7/500
5/5 [==============================] - 0s 11ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 8/500
5/5 [==============================] - 0s 10ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 9/500
5/5 [==============================] - 0s 5ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 10/500
5/5 [==============================] - 0s 7ms/step - loss: 6565.1626 - mae: 6565.1626
Epoch 11/50

In [ ]:
X_train.shape, y_train.shape

((160,), (160,))

In [ ]:
tf.expand_dims(X_train, axis=-1).shape

TensorShape([160, 1])

In [ ]:
model_2 = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(1)
])

model_2.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.Adam(lr=0.01),
                metrics=["mae"])

model_2.fit(tf.expand_dims(X_train, axis=-1), y_train, epochs=200, verbose=1)

Epoch 1/200
5/5 [==============================] - 2s 6ms/step - loss: 6564.7319 - mae: 6564.7319
Epoch 2/200
5/5 [==============================] - 0s 5ms/step - loss: 6564.6421 - mae: 6564.6421
Epoch 3/200
5/5 [==============================] - 0s 5ms/step - loss: 6564.6377 - mae: 6564.6377
Epoch 4/200
5/5 [==============================] - 0s 5ms/step - loss: 6564.5728 - mae: 6564.5728
Epoch 5/200
5/5 [==============================] - 0s 5ms/step - loss: 6564.5171 - mae: 6564.5171
Epoch 6/200
5/5 [==============================] - 0s 5ms/step - loss: 6564.4819 - mae: 6564.4819
Epoch 7/200
5/5 [==============================] - 0s 6ms/step - loss: 6564.4399 - mae: 6564.4399
Epoch 8/200
5/5 [==============================] - 0s 5ms/step - loss: 6564.4033 - mae: 6564.4033
Epoch 9/200
5/5 [==============================] - 0s 6ms/step - loss: 6564.3608 - mae: 6564.3608
Epoch 10/200
5/5 [==============================] - 0s 5ms/step - loss: 6564.3369 - mae: 6564.3369
Epoch 11/200
5/5 [=

In [ ]:
housing_data = tf.keras.datasets.boston_housing.load_data(
    path='boston_housing.npz', test_split=0.2, seed=113
)
type(housing_data)

tuple

In [ ]:
(X_train, y_train), (X_test, y_test) = housing_data
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((404, 13), (404,), (102, 13), (102,))

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(8),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(1)
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["mae"])

model.fit(X_train, y_train, epochs=300, verbose=1)

Epoch 1/300
13/13 [==============================] - 4s 6ms/step - loss: 104.9326 - mae: 104.9326
Epoch 2/300
13/13 [==============================] - 0s 6ms/step - loss: 63.2487 - mae: 63.2487
Epoch 3/300
13/13 [==============================] - 0s 4ms/step - loss: 45.5395 - mae: 45.5395
Epoch 4/300
13/13 [==============================] - 0s 4ms/step - loss: 28.3137 - mae: 28.3137
Epoch 5/300
13/13 [==============================] - 0s 4ms/step - loss: 14.9809 - mae: 14.9809
Epoch 6/300
13/13 [==============================] - 0s 4ms/step - loss: 11.7641 - mae: 11.7641
Epoch 7/300
13/13 [==============================] - 0s 7ms/step - loss: 10.9959 - mae: 10.9959
Epoch 8/300
13/13 [==============================] - 0s 5ms/step - loss: 9.9797 - mae: 9.9797
Epoch 9/300
13/13 [==============================] - 0s 5ms/step - loss: 9.3460 - mae: 9.3460
Epoch 10/300
13/13 [==============================] - 0s 5ms/step - loss: 8.7630 - mae: 8.7630
Epoch 11/300
13/13 [=======================

In [ ]:
pd.DataFrame(X_train).isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
dtype: int64

In [ ]:
pd.DataFrame(X_train).dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
dtype: object

In [ ]:
pd.DataFrame(y_train).isna().sum()

0    0
dtype: int64

In [ ]:
model.evaluate(X_test, y_test)

4/4 [==============================] - 0s 4ms/step - loss: 3.9248 - mae: 3.9248


[3.924795389175415, 3.924795389175415]

In [ ]:
model_2 = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(8, activation="relu"),
    tf.keras.layers.Dense(5, activation="relu"),
    tf.keras.layers.Dense(1)
])

model_2.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["mae"])

model_2.fit(X_train, y_train, epochs=300, verbose=1)

Epoch 1/300
13/13 [==============================] - 1s 2ms/step - loss: 105.5930 - mae: 105.5930
Epoch 2/300
13/13 [==============================] - 0s 3ms/step - loss: 60.0159 - mae: 60.0159
Epoch 3/300
13/13 [==============================] - 0s 3ms/step - loss: 21.9605 - mae: 21.9605
Epoch 4/300
13/13 [==============================] - 0s 2ms/step - loss: 10.0392 - mae: 10.0392
Epoch 5/300
13/13 [==============================] - 0s 3ms/step - loss: 7.7494 - mae: 7.7494
Epoch 6/300
13/13 [==============================] - 0s 2ms/step - loss: 7.0866 - mae: 7.0866
Epoch 7/300
13/13 [==============================] - 0s 3ms/step - loss: 6.4646 - mae: 6.4646
Epoch 8/300
13/13 [==============================] - 0s 2ms/step - loss: 6.1602 - mae: 6.1602
Epoch 9/300
13/13 [==============================] - 0s 2ms/step - loss: 5.9823 - mae: 5.9823
Epoch 10/300
13/13 [==============================] - 0s 2ms/step - loss: 5.9593 - mae: 5.9593
Epoch 11/300
13/13 [=============================

In [ ]:
model_2.evaluate(X_test, y_test)

4/4 [==============================] - 0s 8ms/step - loss: 3.9345 - mae: 3.9345


[3.9344756603240967, 3.9344756603240967]