In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
X = tf.range(-100, 101, 1)
X

<tf.Tensor: shape=(201,), dtype=int32, numpy=
array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1,    0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
         10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
     

In [13]:
y = 2 * (X ** 2) + 3 * X + 4

In [14]:
y

<tf.Tensor: shape=(201,), dtype=int32, numpy=
array([19704, 19309, 18918, 18531, 18148, 17769, 17394, 17023, 16656,
       16293, 15934, 15579, 15228, 14881, 14538, 14199, 13864, 13533,
       13206, 12883, 12564, 12249, 11938, 11631, 11328, 11029, 10734,
       10443, 10156,  9873,  9594,  9319,  9048,  8781,  8518,  8259,
        8004,  7753,  7506,  7263,  7024,  6789,  6558,  6331,  6108,
        5889,  5674,  5463,  5256,  5053,  4854,  4659,  4468,  4281,
        4098,  3919,  3744,  3573,  3406,  3243,  3084,  2929,  2778,
        2631,  2488,  2349,  2214,  2083,  1956,  1833,  1714,  1599,
        1488,  1381,  1278,  1179,  1084,   993,   906,   823,   744,
         669,   598,   531,   468,   409,   354,   303,   256,   213,
         174,   139,   108,    81,    58,    39,    24,    13,     6,
           3,     4,     9,    18,    31,    48,    69,    94,   123,
         156,   193,   234,   279,   328,   381,   438,   499,   564,
         633,   706,   783,   864,   949,  1

In [24]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, name="hidden_layer_1", input_shape=[1], activation="relu"),
    tf.keras.layers.Dense(5, name="hidden_layer_2", activation="relu"),
    tf.keras.layers.Dense(1, name="output_layer", activation="relu")
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=["mae"])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_layer_1 (Dense)      (None, 10)                20        
                                                                 
 hidden_layer_2 (Dense)      (None, 5)                 55        
                                                                 
 output_layer (Dense)        (None, 1)                 6         
                                                                 
Total params: 81
Trainable params: 81
Non-trainable params: 0
_________________________________________________________________


In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X.numpy(), y.numpy(), test_size=0.2)

In [26]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((160,), (160,), (41,), (41,))

In [28]:
model.fit(X_train, y_train, epochs=500, verbose=1)

Epoch 1/500
5/5 [==============================] - 0s 4ms/step - loss: 6678.0376 - mae: 6678.0376
Epoch 2/500
5/5 [==============================] - 0s 4ms/step - loss: 6677.9897 - mae: 6677.9897
Epoch 3/500
5/5 [==============================] - 0s 4ms/step - loss: 6677.9424 - mae: 6677.9424
Epoch 4/500
5/5 [==============================] - 0s 4ms/step - loss: 6677.8945 - mae: 6677.8945
Epoch 5/500
5/5 [==============================] - 0s 3ms/step - loss: 6677.8467 - mae: 6677.8467
Epoch 6/500
5/5 [==============================] - 0s 4ms/step - loss: 6677.7993 - mae: 6677.7993
Epoch 7/500
5/5 [==============================] - 0s 5ms/step - loss: 6677.7515 - mae: 6677.7515
Epoch 8/500
5/5 [==============================] - 0s 5ms/step - loss: 6677.7041 - mae: 6677.7041
Epoch 9/500
5/5 [==============================] - 0s 5ms/step - loss: 6677.6572 - mae: 6677.6572
Epoch 10/500
5/5 [==============================] - 0s 5ms/step - loss: 6677.6094 - mae: 6677.6094
Epoch 11/500
5/5 [=

In [32]:
X_train.shape, y_train.shape

((160,), (160,))

In [34]:
model_2 = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(1)
])

model_2.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["mae"])

model_2.fit(X_train, y_train, epochs=100, verbose=1)

Epoch 1/100


ValueError: ignored